name: Run algorithm

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Compile source files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile in profile mode
        run: scripts/build.sh profile-generate

      - name: Run in profile mode
        run: python scripts/in.py CMT1 | time -p build/main.exe

      - name: Compile in release mode
        run: scripts/build.sh profile-use

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: build/main.exe

  solve:
    name: Run algorithm
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        problem: ["CMT1", "CMT2", "CMT3", "CMT4", "CMT5"]
        steps: [0, 1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: executable
          path: build/

      - name: Initialize working space
        run: |
          mkdir result
          chmod +x build/main.exe

      - name: Run algorithm
        run: |
          exitcode=0
          set +e
          let begin=5*${{ matrix.steps }}+1
          let end=$begin+4
          for i in $(seq $begin $end)
          do
            echo "RUN #$i"
            out=$(python scripts/in.py ${{ matrix.problem }}) && echo "$out" | time -po /dev/stdout build/main.exe | python scripts/out.py ${{ matrix.problem }}
            this_exitcode=$?

            if [ $this_exitcode -ne 0 ]
            then
              echo "::warning::Exit code $this_exitcode at run #$i"
              exitcode=1
            fi
          done

          exit $exitcode

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: solution-${{ matrix.problem }}-${{ matrix.steps }}
          path: result/*

  summary:
    name: Summarize results
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: solve

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download results
        uses: actions/download-artifact@v4
        with:
          path: result/
          pattern: solution-*
          merge-multiple: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Summarize results
        run: python scripts/summary.py

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: result/*
